### ISSUE TITLE
No way for users to define LICENSE_AMPL

### ISSUE THREAD

**Issue by yoctozepto** [eu-nebulous/sal-scripts#19]
In-test variants had hardcoded `LICENSE_AMPL` value but the end users are not supposed to hack on the scripts. This should be made easily settable.

**Comment by yoctozepto** [comment]
I assigned @rudi as the owner of this issue but please discuss and reassign appropriately to get this issue fixed.

**Comment by rudi** [comment]
The optimiser-controller creates the cluster with all environment variables specified by the user in the GUI, and the solver start script picks up the value of `AMPL_LICENSE` (see https://github.com/eu-nebulous/optimiser-solver/blob/3b39ea002fc2b580dbd0eb217c695b47b9fc7677/start-solver.sh#L11).  

So it should all work already, but maybe the end user documentation does not tell the user to set `AMPL_LICENSE` in the GUI?

**Comment by robert-sanfeliu** [comment]
It has been documented on the wiki how to provide AMPL_LICENSE
