### ISSUE TITLE
Substitute referene to private repo

### ISSUE THREAD

**Issue by robert-sanfeliu** [eu-nebulous/sal-scripts#5]
In https://github.com/eu-nebulous/sal-scripts/blob/main/installation-scripts-onm/MASTER_START_SCRIPT.sh

`sudo -H -u ubuntu bash -c 'helm repo add nebulous https://jmarchel7bulls.github.io/helm-charts/'`

**Comment by jmarchel7bulls** [comment]
changed it to the  https://eu-nebulous.github.io/helm-charts/

**Comment by robert-sanfeliu** [comment]
If I try to open it with a web browser it fails:
![image](https://github.com/eu-nebulous/sal-scripts/assets/172278014/49bf9569-c560-470a-ac7f-943157b4890e)

Is it OK?

Others work: https://netdata.github.io/helmchart/'
